/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
  *       description: Schema for user details in the system.
 *       required:
 *         - email
 *         - name
 *         - firstName
 *         - lastName
 *         - password
 *       properties:
 *         _id:
 *           type: string
 *           description: Unique identifier for the user (auto-generated by MongoDB).
 *         email:
 *           type: string
 *           description: The user's email address (must be unique).
 *           example: user@example.com
 *         name:
 *           type: string
 *           description: Full name of the user.
 *           example: John Doe
 *         firstName:
 *           type: string
 *           description: User's first name.
 *           example: John
 *         lastName:
 *           type: string
 *           description: User's last name.
 *           example: Doe
 *         password:
 *           type: string
 *           description: The user's hashed password.
 *           example: $2a$10$abcdefg1234567890
 *         phone:
 *           type: string
 *           description: The user's phone number.
 *           example: "+1234567890"
 *         socketId:
 *           type: string
 *           description: The WebSocket ID associated with the user for real-time communication.
 *           example: "socket12345"
 *         role:
 *           type: string
 *           description: The user's role in the system.
 *           enum:
 *             - admin
 *             - manager
 *             - user
 *             - guest
 *             - hr
 *             - docteam
 *             - finance
 *             - pipeline
 *           example: user
 *         company:
 *           type: string
 *           description: The ID of the company the user belongs to (reference to Company model).
 *           example: "60d0fe4f5311236168a109ca"
 *         isActive:
 *           type: boolean
 *           description: Whether the user account is active.
 *           example: true
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: The date and time when the user was created.
 *           example: "2023-01-01T12:00:00Z"
 */

const express = require('express');
const router = express.Router();
const userProfileController = require('../controllers/userProfileController');
const authenticateUser = require('../middleware/authenticateUser');

router.use(authenticateUser); 

const multer = require('multer');
const upload = multer({
  storage: multer.memoryStorage(),
  limits: {
    fileSize: 5 * 1024 * 1024 // 5MB limit
  }
});
/**
 * @swagger
 * /api/user-profiles/:
 *   post:
 *     summary: Create a new user profile
 *     tags:
 *       - UserProfile
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *           description: The user object that needs to be added to the system.
 *     responses:
 *       201:
 *         description: User profile successfully created.
 *         content:
 *           application/json:
 *             schema:
 *             $ref: '#/components/schemas/User'
 *       400:
 *         description: Bad request. Validation error or other issue.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   description: Error message.
 *                   example: "Validation failed for the profile data."
  *     security:
 *       - bearerAuth: []
 * components: 
 *   securitySchemes:
 *     bearerAuth:
 *       type: http
 *       scheme: bearer
 *       bearerFormat: JWT
 */

router.post('/', userProfileController.createProfile);
/**
 * @swagger
 * /api/user-profiles/:
 *   get:
 *     summary: Retrieve all profiles within the user's company
 *     tags:
 *       - UserProfile
 *     responses:
 *       200:
 *         description: A list of user profiles within the user's company.
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
*                 $ref: '#/components/schemas/User'
 *       500:
 *         description: Internal server error.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   description: Error message.
 *                   example: "An unexpected error occurred."
 *     security:
 *       - bearerAuth: []
 * components: 
 *   securitySchemes:
 *     bearerAuth:
 *       type: http
 *       scheme: bearer
 *       bearerFormat: JWT
 */
router.get('/', userProfileController.getAllProfiles);
/**
 * @swagger
 * /api/user-profiles/users/active:
 *   get:
 *     summary: Retrieve all active users within the user's company
 *     tags:
 *       - UserProfile
 *     responses:
 *       200:
 *         description: A list of active users within the user's company.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/User'
 *       500:
 *         description: Internal server error.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   description: Indicates whether the request was successful.
 *                   example: false
 *                 message:
 *                   type: string
 *                   description: Error message.
 *                   example: "Failed to fetch active users"
 *                 error:
 *                   type: string
 *                   description: Detailed error message.
 *                   example: "Database connection failed."
  *     security:
 *       - bearerAuth: []
 * components: 
 *   securitySchemes:
 *     bearerAuth:
 *       type: http
 *       scheme: bearer
 *       bearerFormat: JWT
 */

router.get("/users/active", userProfileController.getPublicUsers);
/**
 * @swagger
 *  /api/user-profiles/{userid}:
 *   get:
 *     summary: Retrieve a specific user profile by ID
 *     tags:
 *       - UserProfile
 *     parameters:
 *       - in: path
 *         name: userid
 *         required: true
 *         schema:
 *           type: string
 *           description: The unique identifier of the user profile.
 *           example: 60d0fe4f5311236168a109ca
 *     responses:
 *       200:
 *         description: Successfully retrieved the user profile.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/User'
 *       404:
 *         description: Profile not found.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   description: Error message.
 *                   example: "Profile not found"
 *       500:
 *         description: Internal server error.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   description: Error message.
 *                   example: "An unexpected error occurred."
  *     security:
 *       - bearerAuth: []
 * components: 
 *   securitySchemes:
 *     bearerAuth:
 *       type: http
 *       scheme: bearer
 *       bearerFormat: JWT
 */

router.get("/:userid", userProfileController. getProfileById);
/**
 * @swagger
 * /api/user-profiles/put/{userid}:
 *   put:
 *     summary: Update a user profile by ID
 *     description: Updates the details of an existing user based on their unique ID.
 *     tags:
 *       - UserProfile
 *     parameters:
 *       - in: path
 *         name: userid
 *         required: true
 *         schema:
 *           type: string
 *           description: The unique identifier of the user profile.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
*               $ref: '#/components/schemas/User'
 *     responses:
 *       200:
 *         description: Profile successfully updated.
 *         content:
 *           application/json:
 *             schema:
*               $ref: '#/components/schemas/User'
 *       404:
 *         description: Profile not found.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   description: Error message.
 *                   example: "Profile not found"
 *       500:
 *         description: Internal server error.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   description: Error message.
 *                   example: "An unexpected error occurred."
 *     security:
 *       - bearerAuth: []
 * components: 
 *   securitySchemes:
 *     bearerAuth:
 *       type: http
 *       scheme: bearer
 *       bearerFormat: JWT
 */

router.put("/put/:userid", userProfileController.updateProfileById);
/**
 * @swagger
 * /api/user-profiles/{userId}/toggle-status:
 *   put:
 *     summary: Toggle a user's active status
 *     tags:
 *       - UserProfile
 *     parameters:
 *       - in: path
 *         name: userId
 *         required: true
 *         schema:
 *           type: string
 *           description: The unique identifier of the user.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *             description: The updated user details.
 *     responses:
 *       200:
 *         description: Successfully toggled the user's status.
 *         content:
 *           application/json:
 *             schema:
*             $ref: '#/components/schemas/User'
 *       400:
 *         description: Invalid `isActive` value.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   description: Error message.
 *                   example: "Invalid isActive value. Must be true or false."
 *       404:
 *         description: User not found.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   description: Error message.
 *                   example: "User not found."
 *       500:
 *         description: Internal server error.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   description: Error message.
 *                   example: "Error toggling user status."
 *                 error:
 *                   type: string
 *                   description: Detailed error message.
 *                   example: "Database connection error."
 *     security:
 *       - bearerAuth: []
 * components: 
 *   securitySchemes:
 *     bearerAuth:
 *       type: http
 *       scheme: bearer
 *       bearerFormat: JWT
 */

router.put("/:userId/toggle-status", userProfileController.toggleUserStatus);

router.delete('/remove-image', authenticateUser, userProfileController.removeUserImage);
router.post('/upload-image', upload.single('profileImage'), userProfileController.uploadProfileImage);


module.exports = router;
 