const mongoose = require('mongoose');

const SMTPAccountSchema = new mongoose.Schema({
  company: { type: mongoose.Schema.Types.ObjectId, ref: 'Company', required: true, index: true },
  name: { type: String, required: true },
  provider: {
    type: String,
    enum: ['smtp', 'gmail_oauth', 'office365', 'amazon_ses', 'mailgun', 'sendgrid', 'brevo', 'postmark', 'custom'],
    default: 'smtp',
  },
  fromEmail: { type: String, required: true },
  fromName: { type: String, default: '' },
  replyTo: String,
  host: String,
  port: { type: Number, default: 587 },
  secure: { type: Boolean, default: false },
  username: String,
  passwordEncrypted: String,
  oauthClientId: String,
  oauthClientSecretEncrypted: String,
  oauthRefreshTokenEncrypted: String,
  oauthAccessTokenEncrypted: String,
  oauthTokenExpiresAt: Date,
  apiKeyEncrypted: String,
  region: String,
  domain: String,
  imap: {
    enabled: { type: Boolean, default: false },
    host: String,
    port: { type: Number, default: 993 },
    secure: { type: Boolean, default: true },
    username: String,
    passwordEncrypted: String,
    lastSyncAt: Date,
    lastSyncStatus: { type: String, enum: ['success', 'failed', 'pending'], default: 'pending' },
    lastSyncError: String,
    lastImported: { type: Number, default: 0 },
    lastUid: { type: Number, default: 0 },
  },
  isDefault: { type: Boolean, default: false },
  isFallback: { type: Boolean, default: false },
  priority: { type: Number, default: 10 },
  dailyLimit: { type: Number, default: 1000 },
  sentToday: { type: Number, default: 0 },
  lastResetDate: { type: Date, default: Date.now },
  isActive: { type: Boolean, default: true },
  lastTestedAt: Date,
  lastTestStatus: { type: String, enum: ['success', 'failed', 'pending'], default: 'pending' },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
}, { timestamps: true });

module.exports = mongoose.model('EmailSMTPAccount', SMTPAccountSchema);
